local _, CGM = ...

CGM:RegisterGuide({
    ["name"] = "DM Draft",
    ["itemsToSell"] = { -- Every time the player visits a vendor, these will be automatically sold. These need to be keys and need to be true if they should be sold.

    },
    ["itemsToDelete"] = {},
    [1] = {["type"] = CGM.Types.Accept, ["questID"] = 456, ["text"] = "Pick up {questName}", ["mapID"] = 1438, ["x"] = 58.70, ["y"] = 44.27},
    [2] = {["type"] = CGM.Types.Accept, ["questID"] = 458, ["text"] = "Pick up {questName}", ["mapID"] = 1438, ["x"] = 59.9, ["y"] = 42.5},
    [3] = {["type"] = CGM.Types.Do, ["questID"] = 456, ["text"] = "Do {questName}", ["mapID"] = 1438, ["x"] = 61.11, ["y"] = 42.81},
    [4] = {
        ["type"] = CGM.Types.Deliver,
        ["questID"] = 456,
        ["rewardID"] = 5394,
        ["text"] = "Hand in {questName}",
        ["mapID"] = 1438,
        ["x"] = 58.70,
        ["y"] = 44.27,
    },
    [5] = {["type"] = CGM.Types.Accept, ["questID"] = 457, ["text"] = "Pick up {questName}", ["mapID"] = 1438, ["x"] = 58.70, ["y"] = 44.27},
    [6] = {["type"] = CGM.Types.Accept, ["questID"] = 3117, ["text"] = "Pick up {questName}", ["mapID"] = 1438, ["x"] = 58.70, ["y"] = 44.27},
    [7] = {["type"] = CGM.Types.Deliver, ["questID"] = 458, ["text"] = "Hand in {questName}", ["mapID"] = 1438, ["x"] = 57.76, ["y"] = 45.09},
    [8] = {["type"] = CGM.Types.Accept, ["questID"] = 459, ["text"] = "Pick up {questName}", ["mapID"] = 1438, ["x"] = 57.76, ["y"] = 45.09},
    [9] = {["type"] = CGM.Types.Do, ["questID"] = 459, ["text"] = "Do {questName}", ["mapID"] = 1438, ["x"] = 56.04, ["y"] = 45.96},
    [10] = {
        ["type"] = CGM.Types.Deliver,
        ["questID"] = 459,
        ["rewardID"] = 5398,
        ["text"] = "Hand in {questName}",
        ["mapID"] = 1438,
        ["x"] = 57.76,
        ["y"] = 45.09,
    },
    [11] = {["type"] = CGM.Types.Accept, ["questID"] = 4495, ["text"] = "Pick up {questName}", ["mapID"] = 1438, ["x"] = 60.90, ["y"] = 41.96},
    [12] = {
        ["type"] = CGM.Types.Buy,
        ["unitID"] = 3589,
        ["items"] = {[2512] = 1},
        ["cost"] = 10,
        ["text"] = "Sell junk and buy arrows ({cost})",
        ["mapID"] = 1438,
        ["x"] = 59.31,
        ["y"] = 41.09,
    },
    [13] = {["type"] = CGM.Types.Accept, ["questID"] = 916, ["text"] = "Pick up {questName}", ["mapID"] = 1438, ["x"] = 57.8, ["y"] = 41.7},
    [14] = {["type"] = CGM.Types.Do, ["questID"] = 916, ["text"] = "Kill boars on the way and do {questName}", ["mapID"] = 1438, ["x"] = 56.69, ["y"] = 33.86},
    [15] = {["type"] = CGM.Types.Deliver, ["questID"] = 4495, ["text"] = "Hand in {questName}", ["mapID"] = 1438, ["x"] = 54.59, ["y"] = 32.99},
    [16] = {["type"] = CGM.Types.Accept, ["questID"] = 3519, ["text"] = "Pick up {questName}", ["mapID"] = 1438, ["x"] = 54.59, ["y"] = 32.99},
    [17] = {["type"] = CGM.Types.Do, ["questID"] = 457, ["text"] = "Finish {questName}", ["mapID"] = 1438, ["x"] = 59.38, ["y"] = 35.30},
    [18] = {["type"] = CGM.Types.Deliver, ["questID"] = 3519, ["text"] = "Hand in {questName}", ["mapID"] = 1438, ["x"] = 60.90, ["y"] = 41.96},
    [19] = {["type"] = CGM.Types.Accept, ["questID"] = 3521, ["text"] = "Pick up {questName}", ["mapID"] = 1438, ["x"] = 60.90, ["y"] = 41.96},
    [20] = {["type"] = CGM.Types.Coordinate, ["text"] = "Sell junk", ["mapID"] = 1438, ["x"] = 59.31, ["y"] = 41.09},
    [21] = {["type"] = CGM.Types.Deliver, ["questID"] = 457, ["text"] = "Hand in {questName}", ["mapID"] = 1438, ["x"] = 58.70, ["y"] = 44.27},
    [22] = {["type"] = CGM.Types.Deliver, ["questID"] = 916, ["text"] = "Hand in {questName}", ["mapID"] = 1438, ["x"] = 57.8, ["y"] = 41.7},
    [23] = {["type"] = CGM.Types.Accept, ["questID"] = 917, ["text"] = "Pick up {questName}", ["mapID"] = 1438, ["x"] = 57.8, ["y"] = 41.7},
    [24] = {
        ["type"] = CGM.Types.Deliver,
        ["questID"] = 3117,
        ["text"] = "Hand in {questName} (up the tree)",
        ["requiresLevel"] = 4,
        ["mapID"] = 1438,
        ["x"] = 58.66,
        ["y"] = 40.45,
    },
    [25] = {
        ["type"] = CGM.Types.Train,
        ["text"] = "Train {spells} ({cost})",
        ["spells"] = {[1978] = {["name"] = "Serpent Sting", ["rank"] = 1}, [13163] = {["name"] = "Aspect of the Monkey", ["rank"] = 1}},
        ["cost"] = 200,
        ["requiresLevel"] = 4,
        ["mapID"] = 1438,
        ["x"] = 58.66,
        ["y"] = 40.45,
    },
})
