local _, WOTLKC = ...

WOTLKC:RegisterGuide({
    ["name"] = "Elwynn Forest 1-10",
    [1] = {
        ["type"] = WOTLKC.Types.Accept,
        ["questID"] = 783,
        ["text"] = "Pick up A Threat Within",
        ["map"] = 1429,
        ["x"] = 48.17,
        ["y"] = 42.95,
    },
    [2] = {
        ["type"] = WOTLKC.Types.Deliver,
        ["questID"] = 783,
        ["text"] = "Hand in A Threat Within",
        ["map"] = 1429,
        ["x"] = 48.93,
        ["y"] = 41.60,
    },
    [3] = {
        ["type"] = WOTLKC.Types.Accept,
        ["questID"] = 7,
        ["text"] = "Pick up Kobold Camp Cleanup",
        ["map"] = 1429,
        ["x"] = 48.93,
        ["y"] = 41.60,
    },
    [4] = {
        ["type"] = WOTLKC.Types.Accept,
        ["questID"] = 5261,
        ["text"] = "Pick up Eagan Peltskinner",
        ["map"] = 1429,
        ["x"] = 48.17,
        ["y"] = 42.94,
    },
    [5] = {
        ["type"] = WOTLKC.Types.Deliver,
        ["questID"] = 5261,
        ["text"] = "Hand in Eagan Peltskinner",
        ["map"] = 1429,
        ["x"] = 48.94,
        ["y"] = 40.17,
    },
    [6] = {
        ["type"] = WOTLKC.Types.Accept,
        ["questID"] = 33,
        ["text"] = "Pick up Wolves Across the Border",
        ["map"] = 1429,
        ["x"] = 48.94,
        ["y"] = 40.17,
    },
    [7] = {
        ["type"] = WOTLKC.Types.Do,
        ["isMultiStep"] = true,
        ["questIDs"] = {
            33,
            7
        },
        ["text"] = "Do Wolves Across the Border and Kobold Camp Cleanup",
        ["map"] = 1429,
        ["x"] = 47.04,
        ["y"] = 36.90,
    },
    [8] = {
        ["type"] = WOTLKC.Types.Deliver,
        ["questID"] = 33,
        ["text"] = "Hand in Wolves Across the Border",
        ["map"] = 1429,
        ["x"] = 48.94,
        ["y"] = 40.17,
    },
    [9] = {
        ["type"] = WOTLKC.Types.Deliver,
        ["questID"] = 33,
        ["text"] = "Hand in Kobold Camp Cleanup",
        ["map"] = 1429,
        ["x"] = 48.93,
        ["y"] = 41.60,
    },
    [10] = {
        ["type"] = WOTLKC.Types.Grind,
        ["level"] = 3,
        ["xp"] = 800,
        ["text"] = "Grind until you're level 3, 800 xp",
        ["map"] = 1429,
        ["x"] = 47.81,
        ["y"] = 39.69,
    },
    [11] = {
        ["type"] = WOTLKC.Types.Coordinate,
        ["text"] = "Walk over here",
        ["map"] = 1429,
        ["x"] = 46.66,
        ["y"] = 42.00,
    }
})
